version: "3.9"

services:
  api:
    container_name: api
    build: .
    ports:
      - 3000:3000
    environment:
      - DB_USER=admin
      - DB_PASSWORD=1234
      - DB_HOST=db
      - DB=admin
      - DB_PORT=5432
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app

  db:
    container_name: db
    image: postgres:latest
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
      - POSTGRESS_DB=admin
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d admin"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
